// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {main} from '../models';

export function CreateCategory(arg1:models.Category):Promise<services.CategoryView>;

export function CreateSubItem(arg1:models.WorkSubItem):Promise<models.WorkItem>;

export function CreateWorkItem(arg1:models.WorkItem):Promise<models.WorkItem>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteSubItem(arg1:number):Promise<void>;

export function DeleteWorkItem(arg1:number):Promise<void>;

export function GetWorkItemDetail(arg1:number):Promise<models.WorkItem>;

export function Health():Promise<main.HealthInfo>;

export function ListCategories(arg1:boolean,arg2:string):Promise<Array<services.CategoryView>>;

export function ListWorkItems(arg1:number,arg2:boolean,arg3:string):Promise<Array<services.WorkItemView>>;

export function ReorderCategories(arg1:Array<number>):Promise<void>;

export function ReorderSubItems(arg1:number,arg2:Array<number>):Promise<void>;

export function ReorderWorkItems(arg1:number,arg2:Array<number>):Promise<void>;

export function SetCategoryActive(arg1:number,arg2:boolean):Promise<void>;

export function SetSubItemActive(arg1:number,arg2:boolean):Promise<void>;

export function SetWorkItemActive(arg1:number,arg2:boolean):Promise<void>;

export function UpdateCategory(arg1:number,arg2:models.Category):Promise<services.CategoryView>;

export function UpdateSubItem(arg1:number,arg2:models.WorkSubItem):Promise<models.WorkItem>;

export function UpdateWorkItem(arg1:number,arg2:models.WorkItem):Promise<models.WorkItem>;
