// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {collaboration} from '../models';
import {models} from '../models';
import {masterdata} from '../models';
import {main} from '../models';
import {importers} from '../models';

export function AssignTurns(arg1:Record<string, Array<string>>):Promise<void>;

export function BackupNow():Promise<services.BackupInfo>;

export function BuildMasterDataPackage():Promise<collaboration.MasterDataPackage>;

export function ClearChatUnread():Promise<void>;

export function ClearLogo():Promise<services.SettingsView>;

export function CloseCollabRoom():Promise<void>;

export function ComposeSphNumber(arg1:string,arg2:string):Promise<string>;

export function CreateCategory(arg1:models.Category):Promise<services.CategoryView>;

export function CreateCollabRoom(arg1:number,arg2:string,arg3:string):Promise<collaboration.RoomInfo>;

export function CreateCustomer(arg1:models.Customer):Promise<services.CustomerView>;

export function CreateMaterial(arg1:models.Material):Promise<models.Material>;

export function CreateSph(arg1:services.SphSaveInput):Promise<services.SphDocumentView>;

export function CreateSphRevision(arg1:number):Promise<services.SphDocumentView>;

export function CreateSubItem(arg1:models.WorkSubItem):Promise<models.WorkItem>;

export function CreateTemplate(arg1:models.Template):Promise<services.TemplateView>;

export function CreateVessel(arg1:models.Vessel):Promise<models.Customer>;

export function CreateWorkItem(arg1:models.WorkItem):Promise<models.WorkItem>;

export function DashboardStats():Promise<services.DashboardStats>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteCustomer(arg1:number):Promise<void>;

export function DeleteMaterial(arg1:number):Promise<void>;

export function DeleteSph(arg1:number):Promise<void>;

export function DeleteSubItem(arg1:number):Promise<void>;

export function DeleteSubItems(arg1:Array<number>):Promise<services.DeleteResult>;

export function DeleteTemplate(arg1:number):Promise<void>;

export function DeleteVessel(arg1:number):Promise<void>;

export function DeleteWorkItem(arg1:number):Promise<void>;

export function DeleteWorkItems(arg1:Array<number>):Promise<services.DeleteResult>;

export function DuplicateSph(arg1:number):Promise<services.SphDocumentView>;

export function DuplicateTemplate(arg1:number):Promise<services.TemplateView>;

export function ExportSphExcel(arg1:number):Promise<string>;

export function ExportSphPdf(arg1:number,arg2:string):Promise<string>;

export function GetChatUnread():Promise<number>;

export function GetCollabDefaults():Promise<services.CollabDefaults>;

export function GetCollabSession():Promise<collaboration.UISnapshot>;

export function GetMasterInbox(arg1:string):Promise<masterdata.InboxItem>;

export function GetMasterInboxPayload(arg1:string):Promise<collaboration.MasterDataPackage>;

export function GetSettings():Promise<services.SettingsView>;

export function GetSph(arg1:number):Promise<models.SphDocument>;

export function GetTemplateDetail(arg1:number):Promise<models.Template>;

export function GetWorkItemDetail(arg1:number):Promise<models.WorkItem>;

export function Health():Promise<main.HealthInfo>;

export function ImportBackup():Promise<services.BackupInfo>;

export function InstallMasterData(arg1:string,arg2:string,arg3:Record<string, string>):Promise<masterdata.InstallSummary>;

export function JoinCollabRoom(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function LeaveCollabRoom():Promise<void>;

export function ListBackups():Promise<Array<services.BackupInfo>>;

export function ListCategories(arg1:boolean,arg2:string):Promise<Array<services.CategoryView>>;

export function ListCustomers(arg1:boolean,arg2:string):Promise<Array<services.CustomerView>>;

export function ListDiscoveredRooms():Promise<Array<collaboration.DiscoveredRoom>>;

export function ListImportSheets(arg1:string):Promise<Array<string>>;

export function ListMasterInbox():Promise<Array<masterdata.InboxItem>>;

export function ListMasterSent():Promise<Array<masterdata.SentItem>>;

export function ListMaterials(arg1:boolean,arg2:string):Promise<Array<models.Material>>;

export function ListSph(arg1:string,arg2:string,arg3:number):Promise<Array<services.SphDocumentView>>;

export function ListTemplates(arg1:boolean,arg2:string):Promise<Array<services.TemplateView>>;

export function ListWorkItems(arg1:number,arg2:boolean,arg3:string):Promise<Array<services.WorkItemView>>;

export function LogoDataUrl():Promise<string>;

export function MarkMasterInboxViewed(arg1:string):Promise<void>;

export function OpenBackupFolder():Promise<void>;

export function OpenExportFolder(arg1:string):Promise<void>;

export function ParseImportRows(arg1:string,arg2:string,arg3:importers.ColumnMapping):Promise<Array<importers.PreviewRow>>;

export function PickImportFile():Promise<string>;

export function PickLogo():Promise<services.SettingsView>;

export function PreviewImportSheet(arg1:string,arg2:string):Promise<importers.SheetPreview>;

export function PreviewMasterData(arg1:string):Promise<Array<masterdata.DiffItem>>;

export function PreviewSphNumber(arg1:string):Promise<string>;

export function QuitApp():Promise<void>;

export function RejectMasterData(arg1:string):Promise<void>;

export function ReleaseEdit(arg1:string):Promise<void>;

export function ReorderCategories(arg1:Array<number>):Promise<void>;

export function ReorderSubItems(arg1:number,arg2:Array<number>):Promise<void>;

export function ReorderTemplates(arg1:Array<number>):Promise<void>;

export function ReorderWorkItems(arg1:number,arg2:Array<number>):Promise<void>;

export function RequestEdit(arg1:string):Promise<void>;

export function RestoreBackup(arg1:string):Promise<main.RestoreResult>;

export function RunWorkItemImport(arg1:number,arg2:string,arg3:string,arg4:importers.ColumnMapping,arg5:Array<services.ConfirmRow>):Promise<services.ImportResult>;

export function SendChatMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SendCollabOp(arg1:services.OpPayload):Promise<void>;

export function SendMasterData(arg1:collaboration.MasterDataPackage,arg2:Array<string>):Promise<void>;

export function SetCategoryActive(arg1:number,arg2:boolean):Promise<void>;

export function SetCustomerActive(arg1:number,arg2:boolean):Promise<void>;

export function SetMaterialActive(arg1:number,arg2:boolean):Promise<void>;

export function SetSphStatus(arg1:number,arg2:string):Promise<void>;

export function SetSubItemActive(arg1:number,arg2:boolean):Promise<void>;

export function SetTemplateActive(arg1:number,arg2:boolean):Promise<void>;

export function SetTemplateItems(arg1:number,arg2:Array<services.TemplateItemInput>):Promise<models.Template>;

export function SetVesselActive(arg1:number,arg2:boolean):Promise<void>;

export function SetWorkItemActive(arg1:number,arg2:boolean):Promise<void>;

export function StartDiscoveryListener():Promise<void>;

export function StopDiscoveryListener():Promise<void>;

export function SuggestSphNumber(arg1:string):Promise<string>;

export function SyncPush(arg1:services.SphSaveInput):Promise<void>;

export function Terbilang(arg1:number):Promise<string>;

export function UpdateCategory(arg1:number,arg2:models.Category):Promise<services.CategoryView>;

export function UpdateCustomer(arg1:number,arg2:models.Customer):Promise<models.Customer>;

export function UpdateDraftSph(arg1:number,arg2:services.SphSaveInput):Promise<models.SphDocument>;

export function UpdateMaterial(arg1:number,arg2:models.Material):Promise<models.Material>;

export function UpdateSettings(arg1:services.SettingsInput):Promise<services.SettingsView>;

export function UpdateSubItem(arg1:number,arg2:models.WorkSubItem):Promise<models.WorkItem>;

export function UpdateTemplate(arg1:number,arg2:models.Template):Promise<services.TemplateView>;

export function UpdateVessel(arg1:number,arg2:models.Vessel):Promise<models.Customer>;

export function UpdateWorkItem(arg1:number,arg2:models.WorkItem):Promise<models.WorkItem>;

export function ValidateImportRows(arg1:string,arg2:string,arg3:importers.ColumnMapping,arg4:Array<services.ConfirmRow>):Promise<Array<string>>;
