// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateSubItem(arg1) {
  return window['go']['main']['App']['CreateSubItem'](arg1);
}

export function CreateWorkItem(arg1) {
  return window['go']['main']['App']['CreateWorkItem'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteSubItem(arg1) {
  return window['go']['main']['App']['DeleteSubItem'](arg1);
}

export function DeleteWorkItem(arg1) {
  return window['go']['main']['App']['DeleteWorkItem'](arg1);
}

export function GetWorkItemDetail(arg1) {
  return window['go']['main']['App']['GetWorkItemDetail'](arg1);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ListCategories(arg1, arg2) {
  return window['go']['main']['App']['ListCategories'](arg1, arg2);
}

export function ListWorkItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListWorkItems'](arg1, arg2, arg3);
}

export function ReorderCategories(arg1) {
  return window['go']['main']['App']['ReorderCategories'](arg1);
}

export function ReorderSubItems(arg1, arg2) {
  return window['go']['main']['App']['ReorderSubItems'](arg1, arg2);
}

export function ReorderWorkItems(arg1, arg2) {
  return window['go']['main']['App']['ReorderWorkItems'](arg1, arg2);
}

export function SetCategoryActive(arg1, arg2) {
  return window['go']['main']['App']['SetCategoryActive'](arg1, arg2);
}

export function SetSubItemActive(arg1, arg2) {
  return window['go']['main']['App']['SetSubItemActive'](arg1, arg2);
}

export function SetWorkItemActive(arg1, arg2) {
  return window['go']['main']['App']['SetWorkItemActive'](arg1, arg2);
}

export function UpdateCategory(arg1, arg2) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2);
}

export function UpdateSubItem(arg1, arg2) {
  return window['go']['main']['App']['UpdateSubItem'](arg1, arg2);
}

export function UpdateWorkItem(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkItem'](arg1, arg2);
}
